name: hasura_helper
description: A Hasura GraphQL helper utility to build queries and mutations with ease
version: 1.0.0
homepage: https://github.com/rasitayaz/dart-hasura-helper
repository: https://github.com/rasitayaz/dart-hasura-helper
issue_tracker: https://github.com/rasitayaz/dart-hasura-helper/issues

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
